### ISSUE TITLE
Shouldn't need to change the download URLs

### ISSUE THREAD

**Issue by davidnewcomb** [DomiStyle/docker-tor-browser#15]
I got here first this time and was sick of changing the version number in 5 different places! So I fixed it. The next person only has to change it in 1 place :) We also get a prettier title out of it too, so there is a bonus.

As it's a new feature, I probably ought to have done it on a branch with a merge request and we could have had a chat about it but as it was only a line or two, I just did it on `master`, hope that's ok?

**Comment by DomiStyle** [comment]
I don't see any problems.

That's how it was supposed to work in the first place, I was just in a hurry. :)

**Comment by whalehub** [comment]
Apologies, I've been in the hospital for the past month. The change @davidnewcomb made LGTM as well.
