### ISSUE TITLE
How can I run multiple instances?

### ISSUE THREAD

**Issue by Grunkhead** [DomiStyle/docker-tor-browser#18]
Can anyone explain this? The initial setup for 1 instance was easy, thanks.

**Comment by DomiStyle** [comment]
Sure, just increment the port numbers as you go:

First one: `docker run -d -p 5800:5800 domistyle/tor-browser`

Second one: `docker run -d -p 5801:5800 domistyle/tor-browser`

And so on: `docker run -d -p 580X:5800 domistyle/tor-browser`
