### ISSUE TITLE
Port Change Variable

### ISSUE THREAD

**Issue by capriciousduck** [DomiStyle/docker-tor-browser#19]
Is it possible to assign a port using $PORT so that this app can be deployed on Heroku?

**Comment by DomiStyle** [comment]
It currently isn't possible, no.

**Comment by vital987** [comment]
It is possible with socat and also I did it in my [project)] (https://github.com/vital987/vubuntu) but in this project socat works fine but other services messes with Heroku root access rights, but this project can be customized to run without root permissions :/

**Comment by vital987** [comment]
It is possible with socat and also I did it in my [project](https://github.com/vital987/vubuntu) but in this project socat works fine but other services messes with Heroku root access rights, but this project can be customized to run without root permissions :/

**Comment by vital987** [comment]
> Is it possible to assign a port using $PORT so that this app can be deployed on Heroku?

I've made chromium version which can be deployed on Heroku, you can check it out [here](https://github.com/vital987/chrome-novnc)

**Comment by capriciousduck** [comment]
I guess it won't work fine as the shared memory (SHM) on Heroku is set to only 64MB for the free dyno.

**Comment by vital987** [comment]
> I guess it won't work fine as the shared memory (SHM) on Heroku is set to only 64MB for the free dyno.

One of the reason I switched to chromium cause it has option to disable the usage of shared memory with ```--disable-dev-shm-usage``` flag.

**Comment by vital987** [comment]
> I guess it won't work fine as the shared memory (SHM) on Heroku is set to only 64MB for the free dyno.

I experienced Firefox quitting randomly and so Chromium but after disabling the shared memory usage for chromium, it worked without any issues.

**Comment by lawndoc** [comment]
The newer version of [our base image](https://github.com/jlesage/docker-baseimage-gui) now supports this. Just add the following environment variables to your container at runtime:

- `WEB_LISTENING_PORT`
- `VNC_LISTENING_PORT`

See the README in the base image link above for details.

This issue has been resolved and can be closed @DomiStyle
