### ISSUE TITLE
Can we use this docker as a proxy? so other computer can use tor?

### ISSUE THREAD

**Issue by viponedream** [DomiStyle/docker-tor-browser#22]
run this docker in a router as a proxy, all other computer can use tor ?
how can we do that?

**Comment by whalehub** [comment]
That use case is not supported by this Docker image.

**Comment by davidnewcomb** [comment]
You could probably do that with: https://github.com/davidnewcomb/docker-tor-server    (shameless plug!)
You could tell squid to tunnel its requests over the SOCKS5 port which is set up.
