### ISSUE TITLE
Set up similar to whonix?

### ISSUE THREAD

**Issue by raisen** [DomiStyle/docker-tor-browser#27]
This is more of a question than a bug report. On Whonix, there are 2 VMs: gateway and workstation. Gateway runs tor and workstation runs tor browser that only has network access to the gateway VM network. Workstation also has many firewall rules in place to prevent DNS leaks, etc.

Do you see an advantage of using docker-compose with 2 containers similar to the Whonix VMs? I could try to submit a PR but before doing so I wonder if this is worthwhile doing.

**Comment by lawndoc** [comment]
I don't see the advantage in having 2 containers. Unless there is something I'm missing, it would just add complexity with no real functionality/privacy added.

**Comment by raisen** [comment]
I think the main idea of Whonix having 2 VMs is to make sure all the network traffic goes through tor. In the case for this project, the container that runs Tor Browser would only have network access to the container running the tor daemon. 

Whonix has [a repo](https://github.com/Whonix/whonix-firewall) with its firewall rules. It's quite complex though so it'd take me some time to incorporate into this repo. [This project](https://securityonline.info/dockernymous-whonix-gateway/) is working on a similar solution.

**Comment by lawndoc** [comment]
Do you have evidence that this container leaks network traffic outside of the tor network? If so, we can look at your idea as a potential fix for that. If not, we would just be spending time and adding complexity in order to solve problems that we don't have.
