### ISSUE TITLE
Automatic build pipeline has stopped running

### ISSUE THREAD

**Issue by whalehub** [DomiStyle/docker-tor-browser#30]
@DomiStyle The build pipeline which publishes a new Docker image on each commit last ran on 31.08.2022.

**Comment by DomiStyle** [comment]
It looks like this is due to the new restrictions on the Gitlab Free tier, might be a good idea to switch over to Github Actions.

Will have to take a look at their syntax though since I'm used to Gitlab's CI.

**Comment by DomiStyle** [comment]
@lawndoc I wouldn't mind if somebody configured a Github Actions pipeline. I will probably only have some time for this next week.

**Comment by DomiStyle** [comment]
@whalehub Automatic builds work now, including automatically checking for new Tor versions. Thanks @lawndoc!

**Comment by whalehub** [comment]
@DomiStyle @lawndoc These files will need to be updated to account for [the changes in this commit.](https://github.com/DomiStyle/docker-tor-browser/commit/5ede7955d8b8aa8a5eed7d1333cd9f00b1f03a3e)

https://github.com/DomiStyle/docker-tor-browser/blob/master/.github/workflows/check-for-update.yml
https://github.com/DomiStyle/docker-tor-browser/blob/master/.github/workflows/build-publish.yml

**Comment by lawndoc** [comment]
I'll work on this today
