### ISSUE TITLE
Noscript settings for websites don't save

### ISSUE THREAD

**Issue by B-Down** [DomiStyle/docker-tor-browser#48]
The third (_Appearance_) and the fourth (_Advanced_) options tabs' settings are fine, they're retained between restarts (they're stored in `profile.defaults/storage/default`).

The first two, though, _General_ and _Per-site Permissions_, they just don't play ball: everything I change there, it's only for the current session.
Whenever I restart the container, they're back to their defaults.

For those two tabs, none of the storage files expected are present.
For reference: [https://forums.informaction.com/viewtopic.php?p=103393#p103393](url)
```css
storage-sync-v2.sqlite
storage-sync-v2.sqlite-shm
storage-sync-v2.sqlite-wal
```

For science, I copied those 3 files from my desktop Tor to the container... to no avail.
Noscript wouldn't use them, so I can only wonder _where_ Noscript is expecting to save those settings, and _why_ it doesn't work...

NB: I also have deployed a Firefox (from J. Lesage) in a container, and Noscript works as expected.

**Comment by lawndoc** [comment]
If you are restarting the container, are you using a volume to persist data across image resets?

**Comment by lawndoc** [comment]
Okay I think I understand the problem now, this seems to be an issue with the volumes not saving the right data. If you want to find out where the NoScript settings are being saved, you can try the following:
- run the container
- change the NoScript settings
- [create a new image from that container](https://www.dataset.com/blog/create-docker-image/)
- run `container-diff` on the original image and the newly created one to see what files have changed

**Comment by lawndoc** [comment]
Glad you were able to solve your problem. Thanks for following up with the details of the fix!
