### ISSUE TITLE
connected to tor but no internet

### ISSUE THREAD

**Issue by eleaner** [DomiStyle/docker-tor-browser#52]
Hi

I see something like that
![image](https://user-images.githubusercontent.com/5169203/233811980-c7235b97-03a6-4bb4-a81c-7a0af8e73a71.png)
any idea on how to fix it?

my docker is running on oracle cloud VPS
the port 5080 (HTTP access) is exposed through traffic and through additional authentication.
there is no direct port exposure from the container

**Comment by lawndoc** [comment]
Have you tried running on a different network? Oracle cloud could be blocking it somehow even though it says connected to Tor.

**Comment by lawndoc** [comment]
stale
